config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]




  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # 使用PUT的方法，做出/admin/categories/sort路徑
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
    end
  end
  # POST /api/v1/subscribe(用POST的方法去接，而因為設計api時有可能會面臨改版，v1、v2是版本的東西，建議可以加。)
  # POST /api/v2/subscribe



end

app/views/shared/backend/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/admin">

      <%= link_to admin_root_path, class: 'navbar-item' do %>
        <i class="fas fa-home"></i>
      <% end %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "廠商", admin_vendors_path, class: 'navbar-item' %>
      <%= link_to "商品", admin_products_path, class: 'navbar-item' %>
      <%= link_to "分類", admin_categories_path, class: 'navbar-item' %>

    </div>
  </div>
</nav>