config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]




  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # 使用PUT的方法，做出/admin/categories/sort路徑
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
    end
  end
  # POST /api/v1/subscribe(用POST的方法去接，而因為設計api時有可能會面臨改版，v1、v2是版本的東西，建議可以加。)
  # POST /api/v2/subscribe



end

app/models/category.rb
class Category < ApplicationRecord
    acts_as_paranoid
    acts_as_list

    # 寫上這段語法，就可以在編輯商品的頁面裡，商品分類那個下拉選單，按照被更改的順序所排列。
    default_scope { order(position: :asc) }

    has_many :products

    validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
    before_action :find_category, only: [:edit, :update, :destroy, :sort]

    def index
        @categories = Category.all.order(position: :asc)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to admin_categories_path, notice: '新增分類成功'
        else
            render :new
        end
    end

    def destroy
        @category.destroy
        redirect_to admin_categories_path, notice: '分類已刪除'
    end

    def sort
        # insert_at是acts_as_list這個套件給的功能，不是rails本身的。
        # 因為position是從1開始(通常程式裡的陣列從0開始)，所以才寫「i+1」。
        category.insert_at(params[:to].to_i + 1)
        render json: {status: 'OK'}
    end


    private

    def find_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
    end
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
    <div class="field">
      <%= form.label :name, '名稱', class: 'label' %>
      <%= form.text_field :name, class: 'input is-medium' %>
    </div>
  
    <%= form.submit class: 'button is-primary is-medium' %>
  <% end %>

app/views/admin/categories/index.html.erb
<h1 class="title">分類列表</h1>

<%= link_to "新增分類", new_admin_category_path, class: 'button' %>

<article class="message">
  <div class="message-body">小提示：可使用拖拉調整分類順序喔！</div>
</article>

<table class="table is-fullwidth has-shadowed">

    <thead>
        <tr>
            <td>名稱</td>
            <td></td>
        </tr>
    </thead>


    <tbody class="sortable-items">
        <% @categories.each do |category| %>

        <tr class="item data-item="<%= dom_id(category) %> >
            <td><i class="fas fa-grip-vertical"></i>  <%= link_to category.name, edit_admin_category_path(category) %></td>
            <td><%= link_to "刪除", admin_category_path(category), method: :delete, data: {confirm: '確認刪除?!'}, class: 'button is-danger is-small' %></td>
        </tr>

      <% end %>
    </tbody>

</table>

app/views/admin/categories/new.html.erb
<h1 class="title">新增分類</h1>
<%= render "form", category: @category %>