config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]




  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # 使用PUT的方法，做出/admin/categories/sort路徑
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
    end
  end
  # POST /api/v1/subscribe(用POST的方法去接，而因為設計api時有可能會面臨改版，v1、v2是版本的東西，建議可以加。)
  # POST /api/v2/subscribe



end

app/models/product.rb
class Product < ApplicationRecord
  include CodeGenerator

  has_rich_text :description
  has_one_attached :cover_image

  # 驗證是否為存在的
  validates :name, presence: true
  # 驗證是否為存在的、並驗證數字是大於0且
  validates :list_price, :sell_price, numericality: { greater_than: 0, allow_nil: true}
  # 驗證是否為獨有的
  validates :code, uniqueness: true

  # relationships
  # 因為在rails5之後，強制要填belongs_to...，但如果有不想填的狀況，可在後面加「optional: true」。
  belongs_to :category, optional: true
  belongs_to :vendor
  has_many :skus
  # 下面這行代表有很多有關sku的巢狀屬性。
  # reject_if: :all_blank代表如果資訊是空的，就無法寫入成功。
  # allow_destroy: true代表打錯時允許被刪除。
  accepts_nested_attributes_for :skus, reject_if: :all_blank, allow_destroy: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
    before_action :find_product, only:[:edit, :update, :destroy]

    def index
        # includes(:vendor)這段是解決n+1的問題
        @products = Product.all.includes(:vendor)
    end

    def new
        @product= Product.new
        # 手動生成一個sku欄位
        @product.skus.build
    end

    def create
        @product = Product.new(product_params)
        
        if @product.save
          redirect_to admin_products_path, notice: '商品已新增'
        else
          render :new
        end
    end

    def edit
    end

    def update
    if @product.update(product_params)
      redirect_to edit_admin_product_path(@product), notice: '商品已更新'
    else
      render :edit
    end
    end 

    def destroy
        @product.destroy
        redirect_to admin_product_path, notice: '商品已刪除'
    end

    private

    def find_product
        @product = Product.friendly.find(params[:id])
    end

    def product_params
    params.require(:product).permit(:name, 
                                    :vendor_id, 
                                    :list_price, 
                                    :sell_price, 
                                    :on_sell, 
                                    :cover_image, 
                                    :category_id,
                                    :description, 
                                    skus_attributes: [
                                      :id, :spec, :quantity, :_destroy
                                    ])
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
    end

    def show
    end
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product]) do |form| %>
    <%= form_with(model: [:admin, product]) do |form| %>

      商品主圖：
      <%= form.file_field :cover_image %>
      <%= image_tag form.object.cover_image.variant(resize: '600x400') if form.object.cover_image.attached? %>

      <hr>

        <div class="columns">
          <div class="column is-6">
            <div class="field">
              <%= form.label :name, '商品名稱', class: 'label' %>
              <%= form.text_field :name, class: 'input is-medium' %>
            </div>
          </div>
          <div class="column is-3">
            <div class="field">
              <%= form.label :vendor_id, '廠商', class: 'label' %>
              <div class="select is-medium is-fullwidth">
                <%= form.collection_select :vendor_id, Vendor.available, :id, :title %>
              </div>
            </div>
          </div>

          <div class="column is-3">
          <div class="field">
            <%= form.label :category_id, '商品分類', class: 'label' %>
            <div class="select is-medium is-fullwidth">
              <%= form.collection_select :category_id, Category.all, :id, :name %>
            </div>
          </div>
        </div>

        </div>
      
        <div class="columns">
          <div class="column">
            <div class="field">
              <%= form.label :list_price, '定價', class: 'label' %>
              <%= form.number_field :list_price, class: 'input is-medium' %>
            </div>
          </div>
          <div class="column">
            <div class="field">
              <%= form.label :sell_price, '售價', class: 'label' %>
              <%= form.number_field :sell_price, class: 'input is-medium' %>
            </div>
          </div>
        </div>
      
      <div class="field">
        <%= form.label :description, '商品描述', class: 'label' %>
        <%= form.rich_text_area :description %>
      </div>


        <h3>庫存項目</h3>
        <div data-controller="product-form" >


          <template data-target="product-form.template">
            <%= form.fields_for :skus, Sku.new, child_index: 'NEW_RECORD' do |sku| %>
              <%= render 'sku_fields', form: sku %>
            <% end %>
          </template>


          <%= form.fields_for :skus do |sku_form| %>
            <%= render 'sku_fields', form: sku_form %>
          <% end %>
          
          <div data-target="product-form.link">
            <%= link_to "新增品項", '#', class: 'button is-light is-small', data: {action: 'product-form#add_sku'} %>
          </div>


        </div>

        <hr>

        <div class="field">
        <%= form.check_box :on_sell %>
        <%= form.label :on_sell, '是否上架？', class: 'checkbox' %>
      </div>
      
        <%= form.submit class: 'button is-primary is-medium' %>
      <% end %>
<% end %>

app/views/admin/products/_sku_fields.html.erb
<div class="columns nested-fields" data-new-record="<%= form.object.new_record? %>">



<div class="column is-6">
  <div class="field">
    <%= form.text_field :spec, placeholder: '規格', class: 'input' %>
  </div>
</div>



<div class="column is-2">
  <div class="field">

    <%= form.number_field :quantity, placeholder: '數量', class: 'input' %>
  </div>
</div>



<div class="column is-1">
  <div class="field">
    <%= link_to "刪除", '#', class: 'button is-danger', data: {action: 'product-form#remove_sku'} %>
    
  </div>
</div>



<%= form.hidden_field :_destroy %>



</div>

app/views/admin/products/edit.html.erb
<h1 class="title">編輯商品</h1>

<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<h1 class="title">商品列表</h1>

<%= link_to "新增商品", new_admin_product_path, class: 'button' %>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>商品名稱</th>
      <th>廠商</th>
      <th>價格</th>
      <th>銷售狀態</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to "#{product.name} [商品編號：#{product.code}]", edit_admin_product_path(product) %></td>
        <td><%= product.vendor.title %></td>
        <td><%= product.list_price %> / <%= product.sell_price %></td>
        <td><%= product.on_sell %></td>
        <td>
          <%= link_to "編輯", edit_admin_product_path(product), class: 'button is-light is-small' %>
          <%= link_to "刪除", admin_product_path(product), method: 'delete', data: { confirm: '確認刪除?!' }, class: 'button is-danger is-small' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1 class="title">新增商品</h1>


<%= render 'form', product: @product %>