config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]




  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # 使用PUT的方法，做出/admin/categories/sort路徑
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
    end
  end
  # POST /api/v1/subscribe(用POST的方法去接，而因為設計api時有可能會面臨改版，v1、v2是版本的東西，建議可以加。)
  # POST /api/v2/subscribe



end

app/models/vendor.rb
class Vendor < ApplicationRecord
    acts_as_paranoid
    validates :title, presence: true



    # 方法1
    scope :available, -> {where(online: true)}

    # 方法2
    # def self.available
    #     where(online: true)
    # end
end

app/controllers/admin/vendors_controller.rb
class Admin::VendorsController < Admin::BaseController
    before_action :find_vendor, only: [:edit, :update, :destroy]

    def index
        @vendors = Vendor.all
    end

    def new
      @product = Product.new
      @product.skus.build
    end  

    def create
        @vendor = Vendor.new(vendor_params)
    
        if @vendor.save
          redirect_to admin_vendors_path, notice: '新增廠商成功！'
        else
          render :new
        end
    end

    def edit
    end

    def update
      if @vendor.update(vendor_params)
        redirect_to edit_admin_vendor_path(@vendor), notice: '資料更新成功！'
      else
        render :edit
      end
    end

    def destroy
        @vendor.destroy
        redirect_to admin_vendors_path, notice: '廠商已刪除'
    end


    private

    def find_vendor
        @vendor = Vendor.find(params[:id])
    end

    def vendor_params
        params.require(:vendor).permit(:title, :description, :online)
    end
end

app/views/admin/vendors/_form.html.erb
<%= form_with(model: [:admin, vendor]) do |form| %>
    <div class="field">
      <%= form.label :title, '名稱', class: 'label' %>
      <%= form.text_field :title, class: 'input' %>
    </div>
  
    <div class="field">
      <%= form.label :description, '說明', class: 'label' %>
      <%= form.text_area :description, class: 'textarea' %>
    </div>
  
    <div class="field">
      <%= form.check_box :online %>
      <%= form.label :online, '正常營運中？', class: 'checkbox' %>
    </div>
  
    <%= form.submit class: 'button is-primary is-medium' %>
  <% end %>

app/views/admin/vendors/edit.html.erb
<h1 class="title">編輯廠商</h1>

<%= render 'form', vendor: @vendor %>

app/views/admin/vendors/index.html.erb
<h1 class="title">廠商列表</h1>

<%= link_to "新增廠商", new_admin_vendor_path, class: 'button is-primary is-small' %>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>名稱</th>
      <th>說明</th>
      <th>狀態</th>
      <th>更新時間</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @vendors.each do |vendor| %>
    <tr>
      <td><%= link_to vendor.title, edit_admin_vendor_path(vendor) %></td>
      <td><%= strip_tags(vendor.description).truncate(100) %></td>
      <td><%= vendor.online %></td>
      <td><%= vendor.updated_at %></td>
      <td>
        <%= link_to "編輯", edit_admin_vendor_path(vendor), class: 'button is-light is-small' %>
        <%= link_to "刪除", admin_vendor_path(vendor), method: :delete, data: {confirm: '確認刪除?!'}, class: 'button is-danger is-small' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/vendors/new.html.erb
<h1 class="title">新增廠商</h1>

<%= render 'form', vendor: @vendor %>